modLoader = "javafml"
loaderVersion = "[50,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "compost"
version = "${version}"
displayName = "Compost"
displayTest = "IGNORE_SERVER_VERSION"
displayURL = "https://github.com/yurisuika/Compost"
issueTrackerURL = "https://github.com/yurisuika/Compost/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Make composters turn your food waste into whatever you want!
'''

[[dependencies.compost]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.5,1.21]"
ordering = "NONE"
side = "SERVER"

[[dependencies.compost]]
modId = "forge"
mandatory = true
versionRange = "[50,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.compost]]
modId = "emi"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.compost]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[14,)"
ordering = "NONE"
side = "CLIENT"