modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "compost"
version = "${version}"
displayName = "Compost"
displayTest = "IGNORE_SERVER_VERSION"
displayURL = "https://github.com/yurisuika/Compost"
issueTrackerURL = "https://github.com/yurisuika/Compost/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Make composters turn your food waste into whatever you want!
'''

[[mixins]]
config = "compost.mixins.json"

[[dependencies.compost]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.3]"
ordering = "NONE"
side = "BOTH"

[[dependencies.compost]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.compost]]
modId = "emi"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.compost]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[13,)"
ordering = "NONE"
side = "CLIENT"