modLoader = "javafml"
loaderVersion = "[1,)"
license = "GNU Lesser General Public License v3.0"

[[mods]]
modId = "compost"
version = "${version}"
displayName = "Compost"
displayTest = "IGNORE_SERVER_VERSION"
displayURL = "https://github.com/yurisuika/Compost"
issueTrackerURL = "https://github.com/yurisuika/Compost/issues"
logoFile = "icon.png"
authors = "yurisuika"
description = '''
Make composters turn your food waste into whatever you want!
'''

[[mixins]]
config = "compost.mixins.json"

[[dependencies.compost]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,1.21.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.compost]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.compost]]
modId = "emi"
type = "optional"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.compost]]
modId = "roughlyenoughitems"
type = "optional"
versionRange = "[17,)"
ordering = "NONE"
side = "CLIENT"